version: '3.7'
services:
  authservice:
    build:
      context: ./authService
    container_name: auth-service
    ports:
      - "3000:3000" 

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: